### ISSUE TITLE
Fails to work in Webpack 5.0.0-beta.22

### ISSUE THREAD

**Issue by ajaybeniwal** [single-spa/single-spa-react#80]
i am trying webpack beta 22 with our existing Single Spa setup but it does not work and gives me the below error 
mount-parcel.js:157 Uncaught (in promise) Error: During 'mount', parcel threw an error: single-spa minified message #9: Parcel parcel-0 must have a valid bootstrap function See https://single-spa.js.org/error/?code=9&arg=parcel-0
    at mount-parcel.js:157
I have made no changes to webpack and its compiles without any webpack compilation error as well

**Comment by filoxo** [comment]
Did you upgrade to single-spa-react v3 from v2? You would need to follow the migration path if so. https://github.com/single-spa/single-spa-react/releases/tag/v3.0.0

**Comment by ajaybeniwal** [comment]
I have upgraded already to "single-spa-react": "3.0.0", 
"webpack": "5.0.0-beta.22",

Source Code 
import React, { useState, useEffect } from "react";
import ParcelComponent from 'single-spa-react/lib/esm/parcel';
import { mountRootParcel } from 'single-spa';

import ErrorImage from 'components/ErrorPage/503Image';
import BarIndicator from "components/LoadingIndicator/BarContainer";

const DefaultErrorNode = <ErrorImage />;
const DefaultLoadingNode = <BarIndicator />;

```
function useMfe(modulePath, { errorNode, loadingNode, fallbackNode, enabled, moduleProps }) {
	const [module, setModule] = useState(null);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState(false);
	const mfeEnabled = window.fetch && window.System && enabled;
	useEffect(() => {
		const fetchModule = async () => {
			setLoading(true);
			try {
				// eslint-disable-next-line no-undef
				const fetchedModule = await window.System.import(modulePath);
				setModule(fetchedModule);
			} catch (moduleError) {
				console.log(moduleError);
				setError(true);
			}

			setLoading(false);
		};

		if (mfeEnabled) fetchModule();
	}, [mfeEnabled]);


	if (!mfeEnabled) {
		return fallbackNode;
	}


	if (error) return errorNode || DefaultErrorNode;
	if (loading) return loadingNode || DefaultLoadingNode;
	if (module) {
		console.log(module);
		return (
			<ParcelComponent
				config={module}
				mountParcel={mountRootParcel}
				wrapWith="section"
				className="app-container"
				preferredLanguage={sessionStorage.getItem("uecp_locale")}
				{...moduleProps}
			/>
		);
	}

	return null;
}

export default useMfe;
```

**Comment by ajaybeniwal** [comment]
The same code works in Webpack 4.x and breaks in the 5.x i capture the mfe module output and they are totally different in 5X and 4X 
<img width="933" alt="Screenshot 2020-07-09 at 11 30 03 PM" src="https://user-images.githubusercontent.com/658004/87060333-fa37ab00-c23c-11ea-8ce9-6c242c5a7b5b.png">
<img width="970" alt="Screenshot 2020-07-09 at 11 29 46 PM" src="https://user-images.githubusercontent.com/658004/87060347-fc9a0500-c23c-11ea-8640-fd7f275d6545.png">

**Comment by ajaybeniwal** [comment]
I figured out it is related with webpack dev server the production build works fine

**Comment by ajaybeniwal** [comment]
I have opened issue in the webpack repository for webpack dev server and closed this requuest

**Comment by joeldenning** [comment]
What version of single-spa-react are you using? What is your webpack config's output.libraryTarget?

**Comment by ajaybeniwal** [comment]
This is related with webpack dev server 
https://github.com/webpack/webpack-dev-server/issues/2484
